### ISSUE TITLE
Cannot get completion for System.Net and other packages

### ISSUE THREAD

**Issue by jacobwpeng** [AlexandreCarlton/ycmd-docker#2]
![image](https://user-images.githubusercontent.com/2852935/47850958-13564a80-de12-11e8-8fef-c622009f38e8.png)
![image](https://user-images.githubusercontent.com/2852935/47850963-181afe80-de12-11e8-9104-70071f5ad802.png)

I guess it's a omnisharp-server bug, but i'm not sure.

**Comment by AlexandreCarlton** [comment]
While I was able to reproduce this using the container, I also observed the same behaviour without it. :(

This leads to me to believe the problem lies with Omnisharp, and not this project (which merely wraps `ycmd` inside a container). As such, I will close this issue.

Thanks for the interest in this project! :)
